### ISSUE TITLE
暑假 2020.08.01

### ISSUE THREAD

**Issue by raptazure** [raptazure/raptazure.github.io#43]
&nbsp; &nbsp; 这里是暑假的一些计划和需要遵守的原则：
- 每天的大部分时间用来学数学
- 主要查收 twitter 和 telegram 的动态
- 只追番不补番（Re0，刀剑，春物，超炮）
- 写代码作为主要的娱乐活动 - mostly rust-lang
- 使用 2Do 配合 GitHub Project 记录每天做的事情

**Comment by CWKSC** [comment]
at least 9 hr/day ... 這個會不會有點難 ...

**Comment by raptazure** [comment]
> at least 9 hr/day ... 这个会不会有点难 ...

08:00-11:00, 14:30-17:30, 20:00-23:00 其实还好 qwq

**Comment by CWKSC** [comment]
qwq 可怕的巨巨

**Comment by raptazure** [comment]
> qwq 可怕的巨巨
> 
> 暑假没有上午时间.webp

正因为我太弱了，才要加倍努力呀 = =
